### ISSUE TITLE
RequireJS for Node

### ISSUE THREAD

**Issue by neverfox** [dbashford/mimosa#195]
Given Mimosa's buy-in to RequireJS, it would be nice to be able to [use it with Node on the server side](http://requirejs.org/docs/node.html). For this to work with Mimosa, however, I think it would require that the `mimosa` command be aware that the server code is going to be a RequireJS module. Peaking at the `app.js` file that Mimosa produces for distribution (which I assume gives a view into what the `mimosa` command runs, it would need to be something like this:

````javascript
var requirejs = require('requirejs');

requirejs.config({
    nodeRequire: require
});

requirejs(['server', 'mimosa-config'], function (server, config) {
    server.startServer(config, function(){});
});
````

And the `server.coffee` module would be something like:
````javascript
define(["express", "consolidate", "./routes"], function(express, engines, routes) {
  return {
    startServer: function(config, callback) {...}
  };
});
````

There's also the "universal" form but I'm not sure if that's appropriate for this case:
````
if (typeof define !== "function") {
  var define = require("amdefine")(module);
}

define(function(require) {
  var engines, express, routes, startServer;
  express = require("express");
  engines = require("consolidate");
  routes = require("./routes");
  return {
    startServer: function(config, callback) {...}
  }
});
````
Not sure if I got that all entirely right but I think that's the general idea. For coffeescript server and modules I'm not so sure how it needs to work; maybe it would require something like [this](https://github.com/jrburke/require-cs):

````javascript
var requirejs = require('requirejs');

requirejs.config({
    nodeRequire: require
});

requirejs(['cs!server', 'cs!mimosa-config'], function (server, config) {
    server.startServer(config, function(){});
});
````

**Comment by Anachron** [comment]
@dbashford @neverfox I believe using pure ES6 is much better now than using requirejs.

**Comment by neverfox** [comment]
@Anachron I've come to the point where I agree.

**Comment by dbashford** [comment]
Going to close this out.

I agree, as it regards node.js development, I feel like using requirejs/amd syntax was never really a good idea.

But, while I'll be investigating other options if only to be learned on them, I still think requirejs is a fantastic tool for building web applications.
