### ISSUE TITLE
Error: Cannot find module 'rimraf'

### ISSUE THREAD

**Issue by xypaul** [dbashford/mimosa#374]
Just upgraded to mimosa@2.1.7 I now get this error:

```
00:07:29 - ERROR - Error pulling in local Mimosa module: Error: Cannot find module 'rimraf'
```

Any ideas what wrong?

I've also tried the latest Mimosa, but that also has no success.

**Comment by dorlovsky** [comment]
if you get this on a clean reinstall on windows you need to blow away your npm cache dir in \AppData\Roaming
