### ISSUE TITLE
Latest Mimosa site build missing documentation

### ISSUE THREAD

**Issue by chrylis** [dbashford/mimosa#436]
The new site layout looks nice and clean, but I can't find the section that discussed configuration of the standard plugins, such as the information added for #141.

**Comment by dbashford** [comment]
It's not missing, its just moved to the mimosa-require module.  I won't be going through all the historical issues to correct that sort of thing.  At the very least the commit is linked in the issue and you can see the diff there.

https://github.com/dbashford/mimosa-require#single-file-optimization-with-almond

**Comment by chrylis** [comment]
The new approach makes a lot of sense, it's just a change that threw me. It might be helpful to note in the Modules and/or Config sections that module-specific configuration is documented in each module's own docs.

**Comment by dbashford** [comment]
file:///Users/dbashford/mygithub/mimosa.io/configuration.html#core

![image](https://cloud.githubusercontent.com/assets/581127/6218706/09613516-b5ef-11e4-8dca-8f80f87cc820.png)

**Comment by chrylis** [comment]
*sigh* I swear that I did actually learn to read once upon a time. Thanks.
