### ISSUE TITLE
mimosa.io has two (different) copies of Bootstrap

### ISSUE THREAD

**Issue by mindjuice** [dbashford/mimosa#437]
Just a quick FYI, I was just taking a look under the covers of the new website to see what you were using and I noticed that site.css contains an embedded copy of Bootstrap 3.3.2 and then later Bootstrap 3.3.1 is loaded in bootstrap.min.js.

**Comment by dbashford** [comment]
I see, so you mean the CSS is `3.3.2` and the JS is `3.3.1`.  I was looking around for multiple copies of the CSS. =)

**Comment by mindjuice** [comment]
Sorry, I must have been smoking something last night.  I somehow thought I saw bootstrap.min.css in my head, even though I typed bootstrap.min.js.  Sorry for the false alarm.
